// @ts-nocheck -- pre-existing @hey-api generated-client type drift (see memory: elimika-ui-typecheck)
import type { AssignmentCardData, AssignmentStatus } from './assignment-types';

export const assignmentFilters: Array<{ label: string; value: AssignmentStatus }> = [
  { label: 'Pending', value: 'pending' },
  // { label: 'Ongoing', value: 'ongoing' },
  { label: 'Overdue', value: 'overdue' },
  { label: 'Graded', value: 'graded' },
  { label: 'All', value: 'all' },
];

const assignments: AssignmentCardData[] = [
  {
    ctaLabel: 'View Submissions',
    dueLabel: 'Due 04/10/24',
    iconTone: 'amber',
    id: 'lesson-1-1',
    instructor: 'Sarah Otieno',
    lesson: 'Lesson 1.1',
    status: 'graded',
    statusLabel: 'Graded',
    subtitle: 'Social Media Best Practices',
  },
  {
    badge: '2 New',
    ctaLabel: 'Grade Now',
    dueLabel: 'Due Oct 07 · 04/12',
    iconTone: 'blue',
    id: 'lesson-1-2',
    instructor: 'Sarah Otieno',
    lesson: 'Lesson 1.2',
    status: 'overdue',
    statusLabel: 'Overdue',
    subtitle: 'Basics of SEO',
  },
  {
    ctaLabel: 'View Submissions',
    dueLabel: 'Due today · 04/24',
    iconTone: 'blue',
    id: 'lesson-1-3-a',
    instructor: 'Sarah Otieno',
    lesson: 'Lesson 1.3',
    metricLabel: '67%',
    metricValue: '16/30 Submitted',
    status: 'overdue',
    statusLabel: 'Overdue',
    studentSummary: 'Instructor: Sarah Otieno',
    subtitle: 'Digital Marketing Strategy',
  },
  {
    ctaLabel: 'View Submissions',
    dueLabel: 'Due Oct 18 · 08/20',
    iconTone: 'blue',
    id: 'lesson-1-4-a',
    instructor: 'Sarah Otieno',
    lesson: 'Lesson 1.4',
    metricLabel: '8%',
    metricValue: '72/30 Submitted',
    status: 'graded',
    statusLabel: 'Graded',
    studentSummary: 'Instructor: Sarah Otieno',
    subtitle: 'Introduction to Google Ads',
  },
  {
    badge: 'New',
    ctaLabel: 'View Submissions',
    dueLabel: 'Due 04/17/24',
    iconTone: 'amber',
    id: 'lesson-1-3-b',
    instructor: 'Sarah Otieno',
    lesson: 'Lesson 1.3',
    metricLabel: '72%',
    metricValue: '12/30 Submitted',
    status: 'ongoing',
    statusLabel: 'Ongoing',
    studentSummary: 'Instructor: Sarah Otieno',
    subtitle: 'Digital Marketing Strategy',
  },
  {
    ctaLabel: 'View Submissions',
    dueLabel: 'Due on 04/30/24',
    iconTone: 'blue',
    id: 'lesson-1-4-b',
    instructor: 'Sarah Otieno',
    lesson: 'Lesson 1.4',
    metricLabel: '198%',
    metricValue: '18/18 Graded',
    status: 'graded',
    statusLabel: 'Graded',
    studentSummary: 'Instructor: Sarah Otieno',
    subtitle: 'Introduction to Google Ads',
  },
  {
    ctaLabel: 'View Submissions',
    dueLabel: 'Due on 10/09 · 08/Gald',
    iconTone: 'blue',
    id: 'lesson-1-5',
    instructor: 'Sarah Otieno',
    lesson: 'Lesson 1.5',
    status: 'graded',
    statusLabel: 'Graded',
    subtitle: 'Campaign Reporting Review',
  },
  {
    ctaLabel: 'View Submissions',
    dueLabel: 'Due on 11/14 · 05/17',
    iconTone: 'blue',
    id: 'lesson-1-6',
    instructor: 'Sarah Otieno',
    lesson: 'Lesson 1.6',
    status: 'graded',
    statusLabel: 'Graded',
    subtitle: 'Google Ads Fundamentals',
  },
];
