name: elimika-application

networks:
  elimika-net-dev:
    external: true

volumes:
  postgres:
    driver: local

services:
  postgres:
    image: "postgres:latest"
    container_name: postgres-dev
    environment:
      - "POSTGRES_DB=blast_wave"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
    ports:
      - "5432:5432"
    networks:
      - elimika-net-dev
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-dev
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9090:8080"
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres-dev:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    networks:
      - elimika-net-dev
    command:
      - "start-dev"
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD-SHELL", "exec timeout 5 bash -c 'echo > /dev/tcp/localhost/8080'"]
      interval: 10s
      timeout: 5s
      retries: 10
