services:
  app:
    container_name: elimika-ui
    image: sarafrika/elimika-ui:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env.local
    ports:
      - '3000:3000'
    restart: always
