import type { Metadata } from "next"
import { Nunito_Sans } from "next/font/google"
import "./globals.css"
import { Toaster } from "@/components/ui/sonner"
import { AuthProvider } from "@/context/auth-provider"

const nunitoSans = Nunito_Sans({
  variable: "--font-sans",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Elimika",
  description: "Generated by create next app"
}

export default function RootLayout({
                                     children
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
      <body
        className={`${nunitoSans.className}  antialiased`}
      >
      {children}
      <Toaster />
      </body>
      </html>
    </AuthProvider>
  )
}
