import {
  BarChart3,
  Code2,
  Database,
  Megaphone,
  Palette,
  Presentation,
  ShieldCheck,
  Sparkles,
} from 'lucide-react';

import type { SkillInsight, SuggestedSkill, VerifiedSkillCategory } from './types';

export const verifiedSkillCategories: VerifiedSkillCategory[] = [
  {
    id: 'graphic-design',
    title: 'Graphic Design',
    group: 'Technical Skills',
    level: 'Intermediate',
    score: 82,
    indicators: 4,
    skills: [
      {
        id: 'adobe-illustrator',
        name: 'Adobe Illustrator',
        level: 'Intermediate',
        score: 78,
        provider: 'Adobe',
        category: 'Design Tools',
        icon: Palette,
        tone: 'muted',
      },
      {
        id: 'data-analysis-design',
        name: 'Data Analysis',
        level: 'Advanced',
        score: 86,
        provider: 'Elimika',
        category: 'Visual Analytics',
        icon: BarChart3,
        tone: 'success',
      },
      {
        id: 'graphic-design-badge',
        name: 'Graphic Design',
        level: 'Intermediate',
        score: 83,
        provider: 'Coursera',
        category: 'Credential',
        icon: ShieldCheck,
        tone: 'warning',
      },
      {
        id: 'advanced-photoshop',
        name: 'Advanced Photoshop',
        level: 'Advanced',
        score: 88,
        hours: '3h',
        provider: 'Adobe',
        category: 'Design Tools',
        icon: Palette,
        tone: 'primary',
      },
    ],
  },
  {
    id: 'data-analysis',
    title: 'Data Analysis',
    group: 'Technical Skills',
    level: 'Intermediate',
    score: 76,
    indicators: 3,
    skills: [
      {
        id: 'excel-fundamentals',
        name: 'Excel Fundamentals',
        level: 'Intermediate',
        score: 74,
        provider: 'Microsoft',
        category: 'Spreadsheet',
        icon: BarChart3,
        tone: 'success',
      },
      {
        id: 'data-analyst',
        name: 'Data Analyst',
        level: 'Advanced',
        score: 81,
        provider: 'Google',
        category: 'Analytics',
        icon: Database,
        tone: 'success',
      },
      {
        id: 'sql-for-data-analysis',
        name: 'SQL for Data Analysis',
        level: 'Advanced',
        score: 84,
        hours: '3h',
        provider: 'Elimika',
        category: 'Database',
        icon: Database,
        tone: 'primary',
      },
    ],
  },
  {
    id: 'web-development',
    title: 'Web Development',
    group: 'Technical Skills',
    level: 'Beginner',
    score: 68,
    indicators: 3,
    skills: [
      {
        id: 'html-css-basics',
        name: 'HTML & CSS Basics',
        level: 'Beginner',
        score: 64,
        provider: 'Meta',
        category: 'Frontend',
        icon: Code2,
        tone: 'primary',
      },
      {
        id: 'html-css-badge',
        name: 'HTML&CSS Basics',
        level: 'Beginner',
        score: 66,
        provider: 'Elimika',
        category: 'Credential',
        icon: Code2,
        tone: 'primary',
      },
      {
        id: 'javascript-basics',
        name: 'JavaScript Basics',
        level: 'Beginner',
        score: 69,
        hours: '6h',
        provider: 'Meta',
        category: 'Frontend',
        icon: Code2,
        tone: 'primary',
      },
    ],
  },
  {
    id: 'public-speaking',
    title: 'Public Speaking',
    group: 'Soft Skills',
    level: 'Advanced',
    score: 88,
    indicators: 4,
    skills: [
      {
        id: 'public-speaker',
        name: 'Public Speaker',
        level: 'Advanced',
        score: 88,
        provider: 'Elimika',
        category: 'Communication',
        icon: Presentation,
        tone: 'warning',
      },
      {
        id: 'presentation-skills',
        name: 'Presentation Skills',
        level: 'Advanced',
        score: 91,
        provider: 'Toastmasters',
        category: 'Communication',
        icon: Presentation,
        tone: 'primary',
      },
      {
        id: 'campaign-storytelling',
        name: 'Campaign Storytelling',
        level: 'Intermediate',
        score: 79,
        provider: 'Google',
        category: 'Marketing',
        icon: Megaphone,
        tone: 'success',
      },
    ],
  },
  {
    id: 'credential-portfolio',
    title: 'Micro-Credentials',
    group: 'Micro-Credentials',
    level: 'Advanced',
    score: 90,
    indicators: 5,
    skills: [
      {
        id: 'verified-data-badge',
        name: 'Verified Data Badge',
        level: 'Advanced',
        score: 92,
        provider: 'Google',
        category: 'Credential',
        icon: ShieldCheck,
        tone: 'success',
      },
      {
        id: 'design-systems-badge',
        name: 'Design Systems Badge',
        level: 'Intermediate',
        score: 84,
        provider: 'Adobe',
        category: 'Credential',
        icon: Palette,
        tone: 'warning',
      },
      {
        id: 'frontend-basics-badge',
        name: 'Frontend Basics Badge',
        level: 'Beginner',
        score: 69,
        provider: 'Meta',
        category: 'Credential',
        icon: Code2,
        tone: 'primary',
      },
    ],
  },
];

export const skillInsights: SkillInsight[] = [
  { name: 'Visual Design', rating: 5 },
  { name: 'Analytical Thinking', rating: 4 },
  { name: 'Presentation Skills', rating: 4 },
  { name: 'Marketing', rating: 3 },
  { name: 'Coding Skills', rating: 3 },
];

export const suggestedSkills: SuggestedSkill[] = [
  {
    id: 'digital-marketing',
    name: 'Digital Marketing',
    level: 2,
    progress: 62,
    icon: Megaphone,
    tone: 'warning',
  },
  {
    id: 'excel-analysis',
    name: 'Excel Analysis',
    level: 2,
    progress: 70,
    icon: BarChart3,
    tone: 'success',
  },
  {
    id: 'visual-storytelling',
    name: 'Visual Storytelling',
    level: 1,
    progress: 46,
    icon: Sparkles,
    tone: 'primary',
  },
];
