#!/bin/bash

# Create .env.local file
cat <<EOF > .env.local
NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL}"
NEXT_PUBLIC_KEYCLOAK_REALM="${NEXT_PUBLIC_KEYCLOAK_REALM}"
NEXTAUTH_URL="${NEXTAUTH_URL}"
NEXTAUTH_SECRET="${NEXTAUTH_SECRET}"
KEYCLOAK_ISSUER="${KEYCLOAK_ISSUER}"
KEYCLOAK_CLIENT_ID="${KEYCLOAK_CLIENT_ID}"
KEYCLOAK_CLIENT_SECRET="${KEYCLOAK_CLIENT_SECRET}"
EOF

echo "✅ .env.local file created!"
