/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { ProfessionalBodyDTO } from './ProfessionalBodyDTO';
import type { TrainingExperienceDTO } from './TrainingExperienceDTO';
import type { UserCertificationDTO } from './UserCertificationDTO';
/**
 * Comprehensive instructor profile including professional qualifications, training experience, certifications, and location data for educational service delivery
 */
export type Instructor = {
    /**
     * **[READ-ONLY]** Email or username of the user who last modified this instructor profile. Used for audit trails and administrative purposes.
     */
    readonly updated_by?: string;
    /**
     * **[REQUIRED]** Reference to the base user account UUID. Links instructor profile to user authentication and personal details.
     */
    user_uuid: string;
    /**
     * **[OPTIONAL]** Geographical latitude coordinate of instructor's primary training location. Used for location-based instructor matching and distance calculations.
     */
    latitude?: number;
    /**
     * **[OPTIONAL]** Geographical longitude coordinate of instructor's primary training location. Used for location-based instructor matching and distance calculations.
     */
    longitude?: number;
    /**
     * **[OPTIONAL]** Professional website or portfolio URL. Used to showcase instructor's work, testimonials, and additional credentials.
     */
    website?: string;
    /**
     * **[OPTIONAL]** Professional biography describing instructor's background, expertise, teaching philosophy, and experience. Used in instructor profiles and course descriptions.
     */
    bio?: string;
    /**
     * **[OPTIONAL]** Professional headline or title that summarizes instructor's expertise and role. Used in search results and instructor listings.
     */
    professional_headline?: string;
    /**
     * **[OPTIONAL]** List of professional bodies and associations the instructor is affiliated with. Used to verify professional standing and credibility.
     */
    professional_bodies?: Array<ProfessionalBodyDTO>;
    /**
     * **[OPTIONAL]** Detailed training and teaching experience history. Documents instructor's practical experience in delivering educational content.
     */
    training_experiences?: Array<TrainingExperienceDTO>;
    /**
     * **[OPTIONAL]** Professional certifications and qualifications held by the instructor. Used to verify expertise and authorize teaching specific subjects.
     */
    certifications?: Array<UserCertificationDTO>;
    formattedLocation?: string;
    profileComplete?: boolean;
    totalProfessionalCredentials?: number;
    /**
     * **[READ-ONLY]** Unique system identifier for the instructor profile. Auto-generated by the system.
     */
    readonly uuid?: string;
    /**
     * **[READ-ONLY]** Complete name of the instructor including titles and credentials. Automatically derived from user profile and professional credentials.
     */
    readonly full_name?: string;
    /**
     * **[READ-ONLY]** Timestamp when the instructor profile was first created. Automatically set by the system.
     */
    readonly created_date?: string;
    /**
     * **[READ-ONLY]** Email or username of the user who created this instructor profile. Used for audit trails and administrative purposes.
     */
    readonly created_by?: string;
    /**
     * **[READ-ONLY]** Timestamp when the instructor profile was last modified. Automatically updated by the system on any changes.
     */
    readonly updated_date?: string;
};

