/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * Student profile information including guardian contacts and academic details. Links to a base user account.
 */
export type Student = {
    /**
     * **[READ-ONLY]** Email or username of the user who last modified this student profile. Used for audit trails.
     */
    readonly updated_by?: string;
    /**
     * **[REQUIRED]** Reference to the base user account UUID. Links student profile to user authentication and personal details.
     */
    user_uuid: string;
    /**
     * **[REQUIRED]** Full name of the primary guardian/parent. This is the main emergency contact for the student.
     */
    first_guardian_name: string;
    /**
     * **[REQUIRED]** Mobile phone number of the primary guardian. Used for emergency contacts and notifications. Should include country code.
     */
    first_guardian_mobile: string;
    /**
     * **[OPTIONAL]** Full name of the secondary guardian/parent. Additional emergency contact for the student.
     */
    second_guardian_name?: string;
    /**
     * **[OPTIONAL]** Mobile phone number of the secondary guardian. Alternative contact for emergencies and notifications. Should include country code.
     */
    second_guardian_mobile?: string;
    primaryGuardianContact?: string;
    secondaryGuardianContact?: string;
    allGuardianContacts?: Array<string>;
    /**
     * **[READ-ONLY]** Unique system identifier for the student profile. Auto-generated by the system.
     */
    readonly uuid?: string;
    /**
     * **[READ-ONLY]** Timestamp when the student profile was first created. Automatically set by the system.
     */
    readonly created_date?: string;
    /**
     * **[READ-ONLY]** Email or username of the user who created this student profile. Used for audit trails.
     */
    readonly created_by?: string;
    /**
     * **[READ-ONLY]** Timestamp when the student profile was last modified. Automatically updated by the system on any changes.
     */
    readonly updated_date?: string;
};

