/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { RoleDTO } from './RoleDTO';
/**
 * Complete user profile information including personal details, authentication, and organizational data
 */
export type User = {
    /**
     * **[READ-ONLY]** Timestamp when the user account was last modified. Automatically updated by the system on any changes.
     */
    readonly modified_date?: string;
    /**
     * **[REQUIRED]** User's given/first name. Used for display purposes and official documentation.
     */
    first_name: string;
    /**
     * **[OPTIONAL]** User's middle name or initial. Can be null or empty.
     */
    middle_name?: string;
    /**
     * **[REQUIRED]** User's family/last name. Used for display purposes and official documentation.
     */
    last_name: string;
    /**
     * **[REQUIRED]** User's primary email address. Must be unique across the system. Used for authentication and notifications.
     */
    email: string;
    /**
     * **[REQUIRED]** User's contact phone number. Should include country code for international numbers.
     */
    phone_number: string;
    /**
     * **[REQUIRED]** User's date of birth in ISO 8601 format (YYYY-MM-DD). Used for age verification and personalization.
     */
    dob: string;
    /**
     * **[REQUIRED]** Unique username for system login. Must be unique across the system. Cannot be changed after creation.
     */
    username: string;
    /**
     * **[OPTIONAL]** UUID of the organization this user belongs to. Links user to their organizational context. Can be null for system administrators.
     */
    organisation_uuid?: string;
    /**
     * **[REQUIRED]** Indicates whether the user account is active and can access the system. Inactive users cannot log in.
     */
    active: boolean;
    /**
     * **[OPTIONAL]** Set of roles assigned to this user. Determines user permissions and access levels within the system. Can be empty for users with no specific roles.
     */
    roles?: Array<RoleDTO>;
    gender?: 'Male' | 'Female' | 'Prefer not to say';
    displayName?: string;
    fullName?: string;
    /**
     * **[READ-ONLY]** Unique system identifier for the user. Auto-generated by the system.
     */
    readonly uuid?: string;
    /**
     * **[READ-ONLY]** URL to the user's profile image/avatar. Automatically generated after image upload.
     */
    readonly profile_image_url?: string;
    /**
     * **[READ-ONLY]** Timestamp when the user account was first created. Automatically set by the system.
     */
    readonly created_date?: string;
};

