name: 'Deploy to Server'

on:
  workflow_run:
    workflows: ['Setup Server']
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Self-Hosted Server
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Setup SSH Connection & Deploy
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > private_key
          chmod 600 private_key

          ssh -i private_key -o StrictHostKeyChecking=no "${{ secrets.SERVER_SSH_USER }}@${{ secrets.SERVER_IP }}" <<'EOF'
            set -e  # Exit script on error

            echo "🛑 Stopping and removing existing containers..."
            # Adjust these commands if the container name is different on your server
            docker stop elimika-ui || true
            docker rm elimika-ui || true

            echo "🚀 Pulling latest Docker image from Docker Hub..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/elimika-ui:latest

            echo "🚀 Starting the application with latest image..."
            docker compose -f ~/products/elimika-ui/docker/compose.yaml up -d

            echo "✅ Deployment complete!"
          EOF
