name: "Deploy to Server"

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    name: Deploy to Self-Hosted Server
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Connection & Deploy
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > private_key
          chmod 600 private_key

          ssh -i private_key -o StrictHostKeyChecking=no "${{ secrets.SERVER_SSH_USER }}@${{ secrets.SERVER_IP }}" <<'EOF'
            set -e  # Exit script on error

            echo "🔑 Logging in to GitHub Container Registry..."
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

            echo "🚀 Pulling latest Docker image..."
            cd ~/products/elimika-ui/docker
            docker compose -f compose.yaml pull

            echo "🚀 Restarting the application with .env.local..."
            docker compose -f compose.yaml up -d --no-deps --build

            echo "🧹 Cleaning up old Docker images..."
            docker system prune -af

            echo "✅ Deployment complete!"
          EOF